name: Generated APK AAB (Upload - Create Artifact To Github Action)

env:
  main_project_module: app
  playstore_name: Frogobox ID

on:
  push:
    branches:
      - 'release/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: "8.9"  # نسخه مناسب را مشخص کنید

      - name: Run gradle tests
        run: gradle test

      - name: Build gradle project
        run: gradle build

      - name: Build apk debug project (APK)
        run: gradle assembleDebug

      - name: Build apk release project (APK)
        run: gradle assemble

      - name: Build app bundle release (AAB)
        run: gradle ${{ env.main_project_module }}:bundleRelease

      - name: Upload APK Debug
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) debug generated
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) release generated
          path: ${{ env.main_project_module }}/build/outputs/apk/release/

      - name: Upload AAB (App Bundle) Release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - App bundle(s) AAB release generated
          path: ${{ env.main_project_module }}/build/outputs/bundle/release/
