name: Generated APK AAB (Upload - Create Artifact To Github Action & Release)

env:
  main_project_module: app
  playstore_name: V2PlusApp

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Get App Version
        run: echo "app_version=$(grep 'versionName' app/build.gradle | awk '{print $2}' | tr -d '\"')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: "8.9"

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Run gradle tests
        run: ./gradlew test


      - name: Build gradle project
        run: ./gradlew build -x lint --continue

      - name: Build apk debug project (APK)
        run: ./gradlew assembleDebug

      - name: Build apk release project (APK)
        run: ./gradlew assemble

      - name: Build app bundle release (AAB)
        run: ./gradlew ${{ env.main_project_module }}:bundleRelease

      - name: Upload APK Debug as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: APK-Debug-${{ env.app_version }}
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/*.apk

      - name: Upload APK Release as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: APK-Release-${{ env.app_version }}
          path: ${{ env.main_project_module }}/build/outputs/apk/release/*.apk

      - name: Upload AAB as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AAB-Release-${{ env.app_version }}
          path: ${{ env.main_project_module }}/build/outputs/bundle/release/*.aab

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.app_version }}
          name: "Release - v${{ env.app_version }}"
          draft: false
          prerelease: false
          generate_release_notes: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK Debug to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.main_project_module }}/build/outputs/apk/debug/*.apk
          tag_name: v${{ env.app_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK Release to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.main_project_module }}/build/outputs/apk/release/*.apk
          tag_name: v${{ env.app_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload AAB to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.main_project_module }}/build/outputs/bundle/release/*.aab
          tag_name: v${{ env.app_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
